name: CI to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_nomitigation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push ipp-crypto without mitigations
        id: docker_build_nomitigation
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          target: build
          build-args: nix_derivation=ipp-nomitigation.nix
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sgx-ipp-crypto:nomitigation

      - name: Image digests
        run: echo ${{ steps.docker_build_nomitigation.outputs.digest }}

  build_mitigation_cf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push ipp-crypto with mitigation CF
        id: docker_build_mitigation_cf
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          target: build
          build-args: nix_derivation=ipp-mitigation-cf.nix
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sgx-ipp-crypto:mitigation-cf

      - name: Image digests
        run: echo ${{ steps.docker_build_mitigation_cf.outputs.digest }}

  build_mitigation_load:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push ipp-crypto with mitigation LOAD
        id: docker_build_mitigation_load
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          target: build
          build-args: nix_derivation=ipp-mitigation-load.nix
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sgx-ipp-crypto:mitigation-load

      - name: Image digests
        run: echo ${{ steps.docker_build_mitigation_load.outputs.digest }}

  build_mitigation_all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push ipp-crypto with mitigation all (cf + load)
        id: docker_build_mitigation_all
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          target: build
          build-args: nix_derivation=ipp-mitigation-all.nix
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sgx-ipp-crypto:mitigation-all

      - name: Image digests
        run: echo ${{ steps.docker_build_mitigation_all.outputs.digest }}

  build_all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push ipp-crypto
        id: docker_build_all
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          target: build
          build-args: nix_derivation=ipp.nix
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sgx-ipp-crypto:latest

      - name: Image digests
        run: echo ${{ steps.docker_build_all.outputs.digest }}
